# Generated by Django 4.2.6 on 2023-11-22 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvailableLocations',
            new_name='AvailableLocation',
        ),
    ]
