# Generated by Django 4.2.6 on 2024-01-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("delivery_boy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryperson",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
