# Generated by Django 4.2.6 on 2023-12-27 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_panel", "0005_remove_shopping_is_canceled_and_more"),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="order_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_panel.shopping",
            ),
        ),
    ]
