# Generated by Django 4.2.6 on 2023-11-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='office_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
