# Generated by Django 4.2.6 on 2023-11-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_myuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='auth_provider',
        ),
    ]
