# Generated by Django 4.2.6 on 2023-12-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_panel", "0002_shoppingpayment_shopping_payment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppingpayment",
            name="status",
            field=models.CharField(
                choices=[("success", "Success"), ("incomplete", "Incomplete")],
                default=1,
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
