# Generated by Django 4.2.6 on 2023-12-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_panel", "0003_shoppingpayment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopping",
            name="total_amount",
        ),
        migrations.AddField(
            model_name="shoppingpayment",
            name="total_amount",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
