# Generated by Django 4.2.6 on 2023-12-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_panel", "0004_remove_shopping_total_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopping",
            name="is_canceled",
        ),
        migrations.RemoveField(
            model_name="shopping",
            name="is_completed",
        ),
        migrations.AddField(
            model_name="shoppingpayment",
            name="is_canceled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shoppingpayment",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
