# Generated by Django 4.2.6 on 2023-12-29 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_panel", "0005_remove_shopping_is_canceled_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliverynotification",
            name="shopping",
        ),
        migrations.RemoveField(
            model_name="shoppingdeliveryperson",
            name="shopping",
        ),
        migrations.AddField(
            model_name="deliverynotification",
            name="shooping_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="user_panel.shoppingpayment",
            ),
        ),
        migrations.AddField(
            model_name="shoppingdeliveryperson",
            name="shopping_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="user_panel.shoppingpayment",
            ),
        ),
    ]
