# Generated by Django 4.2.6 on 2023-12-29 10:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_panel", "0006_remove_deliverynotification_shopping_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopping",
            name="address",
        ),
        migrations.RemoveField(
            model_name="shopping",
            name="del_location",
        ),
        migrations.AddField(
            model_name="shoppingpayment",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shoppingpayment",
            name="del_location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, db_index=True, null=True, srid=4326
            ),
        ),
    ]
