# Generated by Django 4.2.6 on 2023-12-29 10:28

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "user_panel",
            "0007_remove_shopping_address_remove_shopping_del_location_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppingpayment",
            name="hotel_loc",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, db_index=True, null=True, srid=4326
            ),
        ),
    ]
