# Generated by Django 4.2.6 on 2024-01-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_panel", "0008_shoppingpayment_hotel_loc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverynotification",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("accepted", "Accepted"), ("rejected", "Rejected")],
                max_length=20,
                null=True,
            ),
        ),
    ]
