# Generated by Django 4.2.6 on 2023-10-23 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255)),
                ('food_type', models.CharField(max_length=255)),
                ('food_image', models.CharField()),
                ('food_price', models.FloatField()),
                ('description', models.TextField()),
                ('is_veg', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodmenu', to='hotel_panel.hotelsaccount')),
            ],
        ),
    ]
