# Generated by Django 4.2.6 on 2023-12-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel_panel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodmenu",
            name="food_type",
            field=models.CharField(
                choices=[
                    ("bev", "bev"),
                    ("main", "main"),
                    ("starter", "starter"),
                    ("desert", "desert"),
                ],
                max_length=25,
            ),
        ),
    ]
