# Generated by Django 4.2.6 on 2023-10-23 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_panel', '0002_foodmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelowner',
            name='contact',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotelowner',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
