# Generated by Django 4.2.6 on 2023-12-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel_panel", "0002_alter_foodmenu_food_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodmenu",
            name="food_type",
            field=models.CharField(
                choices=[
                    ("bev", "Beverage"),
                    ("main", "Main Course"),
                    ("starter", "Starter"),
                    ("desert", "Dessert"),
                ],
                max_length=25,
            ),
        ),
    ]
