# Generated by Django 4.2.6 on 2023-11-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_panel', '0002_alter_foodmenu_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelsaccount',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotelsaccount',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
