# Generated by Django 4.2.6 on 2023-11-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_panel', '0003_alter_hotelsaccount_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmenu',
            name='offer_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
