# Generated by Django 4.2.6 on 2023-10-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_panel', '0003_hotelowner_contact_hotelowner_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelowner',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotelowner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='hotelowner',
            name='id_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hotelowner',
            name='id_proof',
            field=models.CharField(blank=True, null=True),
        ),
    ]
