# Generated by Django 4.2.6 on 2023-10-23 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel_panel', '0004_alter_hotelowner_contact_alter_hotelowner_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelowner',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hotelowner', to=settings.AUTH_USER_MODEL),
        ),
    ]
