# Generated by Django 4.2.6 on 2023-11-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_panel', '0004_foodmenu_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='offer_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
