# Generated by Django 4.2.6 on 2023-10-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_panel', '0005_alter_hotelowner_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelsaccount',
            old_name='user',
            new_name='owner',
        ),
    ]
