# Generated by Django 4.2.6 on 2023-11-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_panel', '0005_alter_foodmenu_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsaccount',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
