# Generated by Django 4.2.6 on 2023-11-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_panel', '0006_hotelsaccount_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsaccount',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='hotel_profile'),
        ),
    ]
