# Generated by Django 4.2.6 on 2023-10-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_panel', '0006_rename_user_hotelsaccount_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsaccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
