# Generated by Django 4.2.6 on 2023-11-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_panel', '0007_hotelsaccount_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelsaccount',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
