# Generated by Django 4.2.6 on 2023-10-25 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_panel', '0007_hotelsaccount_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelsaccount',
            name='password',
        ),
    ]
