# Generated by Django 4.2.6 on 2023-10-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_panel', '0008_remove_hotelsaccount_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelsaccount',
            name='is_logined',
            field=models.BooleanField(default=True),
        ),
    ]
