# Generated by Django 4.2.6 on 2023-10-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_panel', '0009_hotelsaccount_is_logined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelsaccount',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
