# Generated by Django 4.2.6 on 2023-10-26 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_panel', '0010_alter_hotelsaccount_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelsaccount',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hotelaccount', to='hotel_panel.hotelowner'),
        ),
        migrations.AlterField(
            model_name='hotelsaccount',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
