# Generated by Django 4.2.6 on 2023-10-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_panel', '0011_alter_hotelsaccount_owner_alter_hotelsaccount_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelsaccount',
            name='is_logined',
            field=models.BooleanField(default=False),
        ),
    ]
